### ISSUE TITLE
Make Micrometer optional

### ISSUE THREAD

**Issue by ttddyy** [wavefrontHQ/wavefront-spring-boot#107]
One of the team I work with have an application that does not use micrometer.

In configurations, there are places referencing `WavefrontConfig` from micrometer.
([here](https://github.com/wavefrontHQ/wavefront-spring-boot/blob/master/wavefront-spring-boot/src/main/java/com/wavefront/spring/autoconfigure/WavefrontTracingOpenTracingConfiguration.java#L60), [here](https://github.com/wavefrontHQ/wavefront-spring-boot/blob/master/wavefront-spring-boot/src/main/java/com/wavefront/spring/autoconfigure/WavefrontMetricsConfiguration.java#L41) - this one may relate to #74 )

For opentracing, they seems to be retrieving `source` from `WavefrontConfig`. 

Probably, it could be replaced with a supplier bean like this:
```java
@FunctionalInterface
public interface WavefrontSourceProvider {

	String getSource();

}
```

Then, conditionally create one to use `WavefrontConfig` if micrometer is available.
```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnClass(WavefrontConfig.class)
@ConditionalOnMissingBean(WavefrontSourceProvider.class)
static class MicrometerSourceConfiguration {

	@Bean
	WavefrontSourceProvider wavefrontSourceProvider(WavefrontConfig wavefrontConfig) {
		return wavefrontConfig::source;
	}

}
```

I didn't check other places, but would be nice to make the micrometer optional.

**Comment by snicoll** [comment]
I don't really understand what you mean by "not using micrometer". Do you mean not using metrics? This a starter for Spring Boot and micrometer is a core (i.e. non optional) for metrics.

**Comment by sushantdewan123** [comment]
As Stephane mentioned above, we would like to make the scope of metrics/micrometer as non-optional. Closing this as wont fix.
