### ISSUE TITLE
Guava shading causes ClassNotFoundException

### ISSUE THREAD

**Issue by jonatan-ivanov** [wavefrontHQ/wavefront-spring-boot#123]
It seems `com.wavefront:wavefront-sdk-java:2.6.4` contains shaded Guava which was removed in 2.6.5: https://github.com/wavefrontHQ/wavefront-sdk-java/commit/45b35bdf98aba4c4ccaa922bf522199512baa89c

Other than this can be considered as a breaking change (removing public classes), it also breaks wavefront itself, If I try to use the latest `com.wavefront:wavefront-spring-boot-bom` which resolves `com.wavefront:wavefront-spring-boot:2.2.0` I'm getting a `ClassNotFoundException`:

```
Failed to instantiate [com.wavefront.spring.autoconfigure.WavefrontSleuthSpanHandler]: Factory method 'wavefrontSleuthSpanHandler' threw exception; nested exception is java.lang.NoClassDefFoundError: com/wavefront/java_sdk/com/google/common/collect/Sets
```
root cause: `Caused by: java.lang.ClassNotFoundException: com.wavefront.java_sdk.com.google.common.collect.Sets`

This happens because at least `WavefrontSleuthSpanHandler` depends on some of these shaded classes: https://github.com/wavefrontHQ/wavefront-spring-boot/blob/bde92acecee6ab19ed659f3ab3ae40fc64f9cb55/wavefront-spring-boot/src/main/java/com/wavefront/spring/autoconfigure/WavefrontSleuthSpanHandler.java#L21-L22

and the breaking change broke it.

**Comment by snicoll** [comment]
IMO `WavefrontSleuthSpanHandler.java` should not be relying on that.

**Comment by jonatan-ivanov** [comment]
I would go want step further, IMO `wavefront-sdk` should not be relying on that.

**Comment by oppegard** [comment]
The Guava dependency was removed in #124 (thanks @jonatan-ivanov!). I would also like `wavefront-sdk` to not rely on Guava – it's something we'll consider in a future version.
