### ISSUE TITLE
Span events are not visible in TObs unless removing "_spanSecondaryId" tag

### ISSUE THREAD

**Issue by mhoshi-vm** [wavefrontHQ/wavefront-spring-boot#143]
Related to spring-cloud/spring-cloud-sleuth#2025
Currently the wavefront-spring-boot adds a "_spanSecondaryId" tag when span.events (or annotations) are set.

https://github.com/wavefrontHQ/wavefront-spring-boot/blob/57fecef31d10bc8c8cd3b711fa8f45446ad220c5/wavefront-spring-boot/src/main/java/com/wavefront/spring/autoconfigure/WavefrontSleuthSpanHandler.java#L332-L334

However TObs is not able to properly render the log url when this tag is added.
I have done a simple test, and by removing this flag, we can now see the span events in TObs UI.

**Comment by oppegard** [comment]
Hi @mhoshi-vm, thanks for reporting this and the PR contribution. We're going to investigate further, since Span Events *should* have been working in the past. So it seems like something changed for them to no longer be working.

**Comment by oppegard** [comment]
After further investigation, I'm closing this since we found the issue on the wavefront backend. Thi will be resolved once https://github.com/wavefrontHQ/java-lib/pull/97 is merged and deployed to clusters.
