### ISSUE TITLE
Ability for auto-configure to store auto-negotiated URL and make it available within the configuration bean.

### ISSUE THREAD

**Issue by howardyoo** [wavefrontHQ/wavefront-spring-boot#16]
I've been testing the auto-config and found checking the standard output for auto-negotiated URL (the first URL that you must enter in order to enable the account and start using your Wavefront) to be very cumbersome if you are not running this locally on your dev / test environment.

So, was thinking maybe we can develop a bean that would tell us the following, once the application starts up:

- Whether the application has any auto-negotiated URL so that user can get (without going through the standard output/log) to copy and open it.
- Whether the application currently has well known file with URL and token already populated and user can check their values from a bean
- Other information (like how long ago that happened, and whether it is expired, etc..?)

Just relying on the output messages when the application first starts can work, but is actually not so great if you want to somehow propagate that message automatically to somewhere else... as I can imagine if users would want to notify some third party notification whenever a new negotiation takes place.

**Comment by snicoll** [comment]
That's an interesting idea. If we don't want to look at the logs, I guess it's fair game to assume the services has a web endpoint of some sort to serve traffic.

How about a simple endpoint that provides some metadata about the service? Given that the API lets us get a one time link, we could consider invoking the underlying API automatically to get the user a new link every time it accesses the endpoint. 

Spring Boot has the concept of Actuator Endpoint. We could create a custom one for wavefront that provides that information.

> Whether the application currently has well known file with URL and token already populated and user can check their values from a bean

You can already do that now with `/actuator/env`. Why would you want to read the token?

> Other information (like how long ago that happened, and whether it is expired, etc..?)

How would we get that information from the application?

**Comment by howardyoo** [comment]
That would be great, having the actuator endpoint (is that REST API?).
Hmm.. yeah, I guess you don't want to expose the token via that endpoint.
The original idea was to make sure the user can know, even though they do
not catch the output in standard out, may be able to systematically check
what the application is using.
I guess that information has to be stored somewhere (maybe along with the
token)?

Howard

**Comment by snicoll** [comment]
> I guess that information has to be stored somewhere (maybe along with the

You can call the backend whenever you need to get a one time link. That's what [the starter does](https://github.com/wavefrontHQ/wavefront-spring-boot/blob/b4fe574bd23b23e2724e4f561ed18b1b13e3a2b0/wavefront-spring-boot/src/main/java/com/wavefront/spring/autoconfigure/account/AccountManagementClient.java#L68) when it restores the token from disk.

We can craft an endpoint that gives you back a json with the one time link every time you invoke it. Something like `/actuator/wavefront-freemium` or something. I wouldn't use `/actuator/wavefront` for this as we don't want to use that namespace for something that specific.

On the other hand, if the only information we can expose is the link, that seems a bit overkill to do an endpoint just for that. How about reusing the `/info` endpoint? The downside is that it is public by default.

**Comment by snicoll** [comment]
@howardyoo I've submitted a proposal in #28, a review would be appreciated.
