### ISSUE TITLE
Not seeing trace when using RestTemplate

### ISSUE THREAD

**Issue by doddatpivotal** [wavefrontHQ/wavefront-spring-boot#23]
I have a set of microservices following pattern described here: https://github.com/adamzwickey/todos. In wavefront tracing, i am seeing trace from my edge service to its downstream api and web.  However, my api app uses RestTemplate to call downstream rest services.  Wavefront is not making the connection.  I've found the trace of a call that traversed the service, but the downstream service does not have a parent trace in the tags.  It appears RestTemplate is not sending the appropriate trace information to the downstream services.  What to do?

**Comment by panghy** [comment]
Just to make sure, you have the OpenTracing spring cloud contrib on your classpath right? (we are looking into supporting both OpenTracing, then later OpenTelemetry as well as Spring Sleuth)

Can you try: https://github.com/opentracing-contrib/java-spring-web? Seems like for RestTemplate you need to add an interceptor yourself. Maybe that's it?

**Comment by doddatpivotal** [comment]
@panghy I've now insured that that I have the OpenTracing spring cloud contrib project.  But it looks like I get this in my logs.

`io.opentracing.contrib.spring.tracer.configuration.TracerAutoConfiguration: Tracer bean is not configured! Switching to NoopTracer
`
The repo you sent me said I have to have a OpenTracing tracer bean in my config.  Is there a code reference on how to do this?

**Comment by snicoll** [comment]
@doddatpivotal it is quite hard to give you support with what've you shared so far. I had a quick look the the project above, a few pointers:

* You need Spring Boot `2.3.0.BUILD-SNAPSHOT` as the harmonization of the `WavefrontTracer` had not been released yet.
* If I search on `master` for `opentracing` I get zero hits

You can run your application in [debug mode](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-logging-console-output) and it will print an auto-configuration report on startup. 

The one you should be looking at is `TracerAutoConfiguration`. With the proper dependencies in place, it should look like this:

```
   TracerAutoConfiguration#getTracer:
      Did not match:
         - @ConditionalOnMissingBean (types: io.opentracing.Tracer; SearchStrategy: all) found beans of type 'io.opentracing.Tracer' wavefrontTracer (OnBeanCondition)
```

And

```
   WavefrontTracingConfiguration#wavefrontTracer matched:
      - @ConditionalOnBean (types: com.wavefront.sdk.common.WavefrontSender; SearchStrategy: all) found bean 'wavefrontSender'; @ConditionalOnMissingBean (types: io.opentracing.Tracer; SearchStrategy: all) did not find any beans (OnBeanCondition)
```

**Comment by doddatpivotal** [comment]
Here is the fork of the original Todos app that I was working on.  https://github.com/doddatpivotal/todos. I made all the changes you suggested and it still didn't work.  However they were of course necessary.  In the end, I was creating local scoped RestTemplates in my controller.  I modified the code to so that I created a RestTemplate bean and then autowired it into my controller, and it worked!!!

I guess it makes sense that my locally scoped RestTemplate would not have been adapted to leverage the special span attribution.  But when I had a bean defined and reused, it was annotated properly.  Thank you so much!

**Comment by snicoll** [comment]
> I guess it makes sense that my locally scoped RestTemplate would not have been adapted to leverage the special span attribution

If you create the object yourself it's not going to be instrumented. It's like doing `new MyService()` somewhere in your code and expect that to be a Spring bean.

Can you share the code that you have for `RestTemplate`? I am not sure if you're reporting the issue is fixed or not for you.

**Comment by doddatpivotal** [comment]
Oh yes.  The issue is resolved.  Thank you. 
 https://github.com/doddatpivotal/todos/commit/d6329a76efe79ec12256152705a42c8cd01af4b7

**Comment by snicoll** [comment]
Thanks for sharing. That allows traces to be exported as the bean is going to be wrapped indeed but that configuration does not provide metrics at all. I've added [a comment with a suggestion](https://github.com/doddatpivotal/todos/commit/d6329a76efe79ec12256152705a42c8cd01af4b7#r38666334).
