### ISSUE TITLE
auto-provisioning of customers not working as expected

### ISSUE THREAD

**Issue by dashaun** [wavefrontHQ/wavefront-spring-boot#246]
I'm trying to upgrade [this guide](https://spring.io/guides/tutorials/metrics-and-tracing/) for Spring Boot 3.2.

With Spring Boot 3.2, when I try to create a project, following the documentation, I run into errors.

I tried adding the 3.0.2 BOM and com.wavefront:wavefront-spring-boot-starter

Hoping to get a "freemium" account provisioned.  This is the error that I got.

```
Failed to auto-negotiate a Wavefront api token from https://wavefront.surf. The error was:

this cluster does not support auto-provisioning of customers. Please check your configuration or visit wavefront.com for more information on starting a trial
```

I went back and edited the Spring Boot 2.4.3 version to use Java 17, and it has the same error, so it doesn't feel like it is an issue with Spring Boot 3.2.

**Comment by snicoll** [comment]
`3.0.2` is not compatible with Spring Boot 3.2.x. You need `3.2.0` that hasn't been released yet.

Wavefront.surf is experiencing an issue that's unrelated to this starter. This should be reported to the wavefront support.

**Comment by dashaun** [comment]
3.2.0 has been released.  auto-provisioning is still having an issue, but its unrelated to this starter.

Closing.
