### ISSUE TITLE
Loose Configured URL and ApiToken Using Spring Cloud Starter Kubernetes Config

### ISSUE THREAD

**Issue by doddatpivotal** [wavefrontHQ/wavefront-spring-boot#25]
If you drop the following dependency in the samples application, then even if you configure the following properties, it always generates a new key and uses the developer URI.  I found this behavior in my app and was able to reproduce in the sample app in this repo.  I expect many people will want to use both spring cloud kubernetes and wavefront.  If I remove the depenency and keep the properties in my sample app application.properties, then a new token is not generated.  That is the expected result I want with the dependency.

management.metrics.export.wavefront.api-token=<YOUR_KEY>
management.metrics.export.wavefront.uri=https://surf.wavefront.com

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes-config</artifactId>
			<version>1.1.2.RELEASE</version>
		</dependency>

**Comment by snicoll** [comment]
Thanks for the report, this is a duplicate of #24
