### ISSUE TITLE
Consider renaming project

### ISSUE THREAD

**Issue by snicoll** [wavefrontHQ/wavefront-spring-boot#3]
For consistency with other repositories in this organization it would be nice if the name of this repo starts with `wavefront`. 

I'd suggest `wavefront-spring-boot` as it opens up the possiblity to add more modules to this repo (for instance, the current `autoconfigure` module and a `starter`).

Thanks for the consideration.

**Comment by snicoll** [comment]
Another argument is that the default directory name upon cloning this project is too generic (`springboot-autoconfigure`).

**Comment by panghy** [comment]
Now’s the time, let’s do it.
