### ISSUE TITLE
Rename ~/.wavefront_token to ~/.wavefront_freemium

### ISSUE THREAD

**Issue by snicoll** [wavefrontHQ/wavefront-spring-boot#31]
I think the current `~.wavefront_token` name is confusing and we could use some clarification. 

First and foremost, this is used by the account negotiation as a way to save the token. Whenever we read a token from that file, it is assumed it is a freemium account. If we don't want that, we need a different way of flagging the api token as being from a freemium account, see #28 for a concrete example.

The way the file is named makes it possible for someone to think they can put their existing token so that it is automatically configured for whatever app they are working on. Besides breaking the assumption it's a freemium account, it's also implying that this token is for wavefront.surf. Since there is no way to specify the cluster URI in that file, this can lead to more confusion and errors.

There are other mechanisms in Spring Boot to share properties for several applications (you could use environment variables or system properties with a common startup script). I don't think we should promote editing that file manually as it conflicts with the official configuration keys that Spring Boot already exposes.

A possible solution would be to rename the file to make it crystal clear it is about a freemium account, i.e. `/.wavefront_freemium`.

**Comment by panghy** [comment]
sounds fine to me to rename

**Comment by snicoll** [comment]
Let's go with `~/.wavefront_freemium`
