### ISSUE TITLE
Do not negotiate account in integration tests

### ISSUE THREAD

**Issue by snicoll** [wavefrontHQ/wavefront-spring-boot#56]
At the moment, the account negotiation `EnvironmentPostProcessor` kicks in in integration tests (i.e. `@SpringBootTest`). This has two unwanted side effects:

* Accounts are provisioned by CI engine or wherever the test suite is invoked
* Exporting metrics as part of testing an app does not make much sense unless the user has opt-in for that behaviour. The current arrangement makes it the default and it's not really obvious this is happening.

Changing that will lead a test to fail as we haven't provided a token. This should bring us back to what most other micrometer registries are doing. This can be easily disabled using `management.metrics.export.wavefront.enabled`.

**Comment by snicoll** [comment]
I've also created [an improvement in Spring Boot](https://github.com/spring-projects/spring-boot/issues/21616) to make that disabling a bit more idiomatic.

**Comment by panghy** [comment]
Is this the reason we might be getting a lot of traffic? It's from the integration tests that are being done somewhere?

**Comment by snicoll** [comment]
I don't know what you mean by "a lot of traffic". But if you have a much larger account creation where the dashboard was never accessed, that might be it.

**Comment by panghy** [comment]
That's what we are seeing indeed.
