### ISSUE TITLE
Account negotiation is not disabled with management.metrics.export.wavefront.enabled=false

### ISSUE THREAD

**Issue by dmurat** [wavefrontHQ/wavefront-spring-boot#57]
I think it might be useful to have a property for disabling Wavefront integration altogether.

I tried it and want to use it for development. However, rather than poking with dependencies for deployment in upstream environments, it seems that disabling via simple property might be convenient until a broader agreement in an organization is achieved.

Tnx.

**Comment by dmurat** [comment]
Found a way to do it via `spring.autoconfigure.exclude`:

    spring.autoconfigure.exclude:
      - com.wavefront.spring.actuate.WavefrontEndpointAutoConfiguration
      - com.wavefront.spring.autoconfigure.WavefrontAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.export.wavefront.WavefrontMetricsExportAutoConfiguration

Not quite sure if this is enough since `AccountManagementEnvironmentPostProcessor` still prints out messages about the Wavefront account. Probably is, but the printout is misleading. If possible, maybe it will make sense to add some checks in `AccountManagementEnvironmentPostProcessor` to back off when `WavefrontAutoConfiguration` is disabled.

**Comment by snicoll** [comment]
@dmurat thank you for the report, that's useful information. You can disable Wavefront metrics export using the standard Spring Boot property:

```
management.metrics.export.wavefront.enabled=false
```

> Not quite sure if this is enough since AccountManagementEnvironmentPostProcessor still prints out messages about the Wavefront account. Probably is, but the printout is misleading.

These are unrelated. The account negotiation happens very early in the lifecycle of the application as it potentially mutates the `Environment`. It doesn't and can't know about auto-configurations at this stage.

Having said that, disabling itself if the configuration above is defined seems reasonable so we'll do that.

**Comment by dmurat** [comment]
If I understand correctly, once this improvement is implemented, complete turn off will look like the following:

    management.metrics.export.wavefront.enabled=false
    spring.autoconfigure.exclude:
      - com.wavefront.spring.actuate.WavefrontEndpointAutoConfiguration
      - com.wavefront.spring.autoconfigure.WavefrontAutoConfiguration

Is this correct?

**Comment by snicoll** [comment]
No. You won’t need to exclude auto-configurations. You can actually do this now but the starter will try to negotiate an account anyway as I’ve described above and that’s what this issue will fix.

**Comment by dmurat** [comment]
> No. You won’t need to exclude auto-configurations.

Oh, that's great :-) Thank you.
