### ISSUE TITLE
Potential dependency for older code?

### ISSUE THREAD

**Issue by mikempx** [wavefrontHQ/wavefront-spring-boot#8]
I had a failure when testing Pivotal's "fortune-teller" application whose last commit was back in 2016: https://github.com/spring-cloud-samples/fortune-teller

Steps to reproduce: 
1. install Wavefront for Spring Boot Autoconfigure
* git clone https://github.com/wavefrontHQ/wavefront-spring-boot.git
* cd wavefront-spring-boot
* mvn install
* cd ..
2. install Fortune Teller
* git clone https://github.com/spring-cloud-samples/fortune-teller.git
* cd fortune-teller
* mvn clean package **[FAIL]**
* cd fortune-teller-ui
* Edit pom.xml to add dependency:
groupId: javax.xml.bind
artifactId: jaxb-api
version: 2.3.0

* mvn clean package **[SUCCESS]**
* Edit pom.xml for each service with version equal to 2.0.0-SNAPSHOT 
[NOTE: document does not state to add word **SNAPSHOT**

* Add wavefront.properties for each service in src…main…resources.

* mvn clean package **[FAIL]**
KEY ERROR found in io.spring.cloud.samples.fortuneteller.ui.services.fortunes.FortuneServicePactTest: Caused by: java.lang.IllegalStateException: Could not evaluate condition on io.opentracing.contrib.spring.web.starter.ServerTracingAutoConfiguration#tracingHandlerInterceptor due to org/springframework/boot/web/servlet/FilterRegistrationBean not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:55)

**Comment by panghy** [comment]
Will need to validate after the spring boot and micrometer changes, leaving open for now

**Comment by panghy** [comment]
Closing this since we have overhauled the code, please file a new issue with the "v2" code if it still persists.
