### ISSUE TITLE
Upgrade to Wavefront opentracing SDK 2.1.2

### ISSUE THREAD

**Issue by haosong** [wavefrontHQ/wavefront-spring-boot#85]
Fix is in: https://github.com/wavefrontHQ/wavefront-internal-reporter-java/commit/da09acb438838307db4e6292f61aff2473a9be3c
We need to bump the Wavefront SDK versions to get the fix ^

**Comment by haosong** [comment]
PR for the fix: https://github.com/wavefrontHQ/wavefront-spring-boot/pull/86

**Comment by snicoll** [comment]
Closing in favour of PR #86
