### ISSUE TITLE
API Token Still Required When Sending Data via Proxy

### ISSUE THREAD

**Issue by humphreyh** [wavefrontHQ/wavefront-spring-boot#87]
When `management.metrics.export.wavefront.uri` is pointed at a Wavefront Proxy, apps fail to start-up if the `management.metrics.export.wavefront.apiToken` property is not set:

> Invalid Micrometer configuration detected:
>  - management.metrics.export.wavefront.apiToken was 'null' but it must be set whenever publishing directly to the Wavefront API

Specifying a dummy value for the API token allows the app to start up fine.

**Comment by snicoll** [comment]
Thanks for the report. Can you share the value of the uri that you’ve used?

This is not an issue here but I’d like to understand it better before moving it.

**Comment by humphreyh** [comment]
`http://localhost:2878` but others may have their Proxies at a different address

**Comment by snicoll** [comment]
Thanks for the feedback.

> http://localhost:2878 but others may have their Proxies at a different address

Sure, I understand that but I was interested by the format that you've used. There is no way for the underlying infrastructure to realize that this is a proxy. As [mentioned in the documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics-export-wavefront), you need to use a different format when targeting a proxy. If you do so, Micrometer won't attempt to require an API key.

**Comment by humphreyh** [comment]
Ah ok - thanks. There's a bug in Wavefront documentation
