### ISSUE TITLE
Upgrade to Wavefront opentracing SDK 2.1.3

### ISSUE THREAD

**Issue by srujann** [wavefrontHQ/wavefront-spring-boot#89]
contains performance improvements for wavefront delta counters: https://github.com/wavefrontHQ/wavefront-internal-reporter-java/commit/6b471612055ab3c78d5a027386d287f19bb43c98 and https://github.com/wavefrontHQ/wavefront-internal-reporter-java/commit/bff6dd484d9b28c1d59ff4120644aad7bcc4c112

**Comment by snicoll** [comment]
@srujann no need for both an issue and a PR as one superseded the other. 

Closing in favour of PR #90
