### ISSUE TITLE
expose PCF VCAP_APPLICATION env variables as point tags

### ISSUE THREAD

**Issue by howardyoo** [wavefrontHQ/wavefront-spring-boot#9]
It would be great if wavefront spring boot autoconfigure can also automatically collect and expose important user env variables and also VCAP_APPLICATION variables, for example:
`
{
 "VCAP_APPLICATION": {
  "application_id": "77e57641-29e8-4363-9e82-5f5aeb286a14",
  "application_name": "pcf-hello",
  "application_uris": [
   "pcf-hello.cfapps.io"
  ],
  "application_version": "5e7a0053-7e5c-408a-88f8-5ca513e9f314",
  "cf_api": "https://api.run.pivotal.io",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 800
  },
  "name": "pcf-hello",
  "organization_id": "a78c4ee4-67ca-4105-bb8e-1286c9c2bbec",
  "organization_name": "yooh-org",
  "process_id": "77e57641-29e8-4363-9e82-5f5aeb286a14",
  "process_type": "web",
  "space_id": "23bdb750-4a4b-4d29-a1d5-07a4449afdda",
  "space_name": "development",
  "uris": [
   "pcf-hello.cfapps.io"
  ],
  "users": null,
  "version": "5e7a0053-7e5c-408a-88f8-5ca513e9f314"
 }
}
`

If we can expose these variables as point tags, that would be great, as these point tags are also exposed in PCF container metrics and in that way, we can related which applications are running on which container more easily.

**Comment by snicoll** [comment]
We have a PR for this, see #15 where the outcome of this discussion is that it is already supported by the buildpack in a non opt-in fashion. 

What I understand from this discussion is that we shouldn't do anything here. Thoughts?

**Comment by howardyoo** [comment]
Before we decide on anything, Stephane, what would be the steps for the
customers to expose VCAP_APPLICATION env variable via buildpack?
I'm not the expert in buildpacks, so would like to understand (a little
bit) of what is needed to take place - so that maybe someday we may
document this as a requirement.

**Comment by snicoll** [comment]
> Before we decide on anything, Stephane, what would be the steps for the
customers to expose VCAP_APPLICATION env variable via buildpack?

I don't know. I've shared the issue in the PR already. Here it is for reference: https://github.com/cloudfoundry/java-buildpack/issues/644. Following links lead to https://github.com/cloudfoundry/java-buildpack/issues/748

paging @nebhale

**Comment by howardyoo** [comment]
Ok, thanks.. yeah.. my concern is how easy would the buildpack approach
going to be for the customers... Even though the buildpack approach may be
the right and correct way, if the correct way is not an easy way, sadly the
herd will go elsewhere..

**Comment by nebhale** [comment]
For a user to enable this functionality today, they'd do something like `cf set-env APP JBP_CONFIG_METRIC_WRITER '{enabled: true}'` or the CF manifest-based equivalent of the same.  Note that the objection in that issue was for seven additional attributes which is a subset of everything in `VCAP_APPLICATION` (although the subset that you'd want to do the kind of correlation you're looking for).

Other than what is recommended to me by various metrics gathering experts, I don't have any insight or even a strong opinion on how many attributes is too many, whether they should be on by default, etc. so I'm happy to listen to input.

**Comment by shakuzen** [comment]
While caution should still be taken about adding tags to everything, particularly tags that users didn't explicitly configure/opt-in to themselves, a difference with this project is that it is Wavefront-specific and therefore would only affect Wavefront users. I don't know enough about Wavefront to know the full effect of something like this. The previously mentioned and linked issues may not be a significant problem for Wavefront. I don't know, though.

**Comment by thepeterstone** [comment]
@howardyoo This doesn't seem like a desirable thing to add based on the discussion here and in the linked tickets - I'm inclined to close this, do you have any objections?

**Comment by howardyoo** [comment]
Sounds good to me!
