### ISSUE TITLE
Wavefront libraries not compatible with Spring boot 2.4.1

### ISSUE THREAD

**Issue by gkulkarni32** [wavefrontHQ/wavefront-spring-boot#93]
Hello,

I am working with spring boot 2.4.1 version and added the following dependencies for observability integration with wavefront. It did not work with version 2.4.1, I had to change the version to 2.3.x to get this working. 

```
<dependency>
		  <groupId>com.wavefront</groupId>
		  <artifactId>wavefront-spring-boot-starter</artifactId>
		</dependency>		
		 <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
            <version>2.2.2.RELEASE</version>
         </dependency>
```

Can you please confirm if spring boot 2.4.1 is not compatible. Also when we are planning to release the update if it's not compatible.

Thanks
Geeta

**Comment by snicoll** [comment]
Hello,

The best way to get started and get an answer to that question is start.spring.io. 

You are right that the current GA release of this starter is not fully compatible yet. The version of sleuth that you've specified is from a release train that's not compatible with Spring Boot 2.4.x so there's that. The release train of Spring Cloud that's compatible with 2.4 is not GA yet and is a major so we have to catch up. 

If you create a new project and select the dependencies that you need you'll get 2.1.0-SNAPSHOT that's a work in progress towards 2.4.x compatibility. Timing wise I'd like to get a GA out once Spring Cloud 2020.0 is (weeks from now).

**Comment by gkulkarni32** [comment]
Thanks for the update @snicoll

**Comment by snicoll** [comment]
I've pinned our dependencies to what start.spring.io serves at the moment (see [this recent commit](https://github.com/wavefrontHQ/wavefront-spring-boot/commit/2c1f370e265644d30cc065cd2b6d20da81cf047c)). If you're not using Sleuth, the current GA should work just fine with Spring Boot 2.4. 

I am going to close this issue now, please watch #94 for the upgrade follow-up. Thanks for reporting it!
